# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sysmanui.ui'
#
# Created: Tue Apr  1 17:59:39 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(510, 252)
        self.tabbedPanel = QtGui.QTabWidget(Form)
        self.tabbedPanel.setGeometry(QtCore.QRect(10, 10, 491, 221))
        self.tabbedPanel.setObjectName(_fromUtf8("tabbedPanel"))
        self.cpuLoadTab = QtGui.QWidget()
        self.cpuLoadTab.setObjectName(_fromUtf8("cpuLoadTab"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.cpuLoadTab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 451, 141))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.gridLayoutWidget_3)
        self.progressBar.setProperty("value", 100)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_3.addWidget(self.progressBar, 1, 0, 1, 1)
        self.progressBar_2 = QtGui.QProgressBar(self.gridLayoutWidget_3)
        self.progressBar_2.setMaximum(100)
        self.progressBar_2.setProperty("value", 100)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.gridLayout_3.addWidget(self.progressBar_2, 3, 0, 1, 1)
        self.tabbedPanel.addTab(self.cpuLoadTab, _fromUtf8(""))
        self.cpuInfoTab = QtGui.QWidget()
        self.cpuInfoTab.setObjectName(_fromUtf8("cpuInfoTab"))
        self.gridLayoutWidget = QtGui.QWidget(self.cpuInfoTab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 9, 471, 171))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cpufreq = QtGui.QLabel(self.gridLayoutWidget)
        self.cpufreq.setObjectName(_fromUtf8("cpufreq"))
        self.gridLayout.addWidget(self.cpufreq, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.cpucores = QtGui.QLabel(self.gridLayoutWidget)
        self.cpucores.setObjectName(_fromUtf8("cpucores"))
        self.gridLayout.addWidget(self.cpucores, 2, 1, 1, 1)
        self.cpumodel = QtGui.QLabel(self.gridLayoutWidget)
        self.cpumodel.setObjectName(_fromUtf8("cpumodel"))
        self.gridLayout.addWidget(self.cpumodel, 0, 1, 1, 1)
        self.flags = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.flags.setFont(font)
        self.flags.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.flags.setWordWrap(True)
        self.flags.setObjectName(_fromUtf8("flags"))
        self.gridLayout.addWidget(self.flags, 4, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.cpucache = QtGui.QLabel(self.gridLayoutWidget)
        self.cpucache.setObjectName(_fromUtf8("cpucache"))
        self.gridLayout.addWidget(self.cpucache, 3, 1, 1, 1)
        self.tabbedPanel.addTab(self.cpuInfoTab, _fromUtf8(""))
        self.memInfoTab = QtGui.QWidget()
        self.memInfoTab.setObjectName(_fromUtf8("memInfoTab"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.memInfoTab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 471, 171))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.memtotal = QtGui.QLabel(self.gridLayoutWidget_2)
        self.memtotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.memtotal.setObjectName(_fromUtf8("memtotal"))
        self.gridLayout_2.addWidget(self.memtotal, 0, 1, 1, 1)
        self.memfree = QtGui.QLabel(self.gridLayoutWidget_2)
        self.memfree.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.memfree.setObjectName(_fromUtf8("memfree"))
        self.gridLayout_2.addWidget(self.memfree, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 3, 0, 1, 1)
        self.swaptotal = QtGui.QLabel(self.gridLayoutWidget_2)
        self.swaptotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.swaptotal.setObjectName(_fromUtf8("swaptotal"))
        self.gridLayout_2.addWidget(self.swaptotal, 3, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 2, 0, 1, 1)
        self.memused = QtGui.QLabel(self.gridLayoutWidget_2)
        self.memused.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.memused.setObjectName(_fromUtf8("memused"))
        self.gridLayout_2.addWidget(self.memused, 2, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 4, 0, 1, 1)
        self.swapfree = QtGui.QLabel(self.gridLayoutWidget_2)
        self.swapfree.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.swapfree.setObjectName(_fromUtf8("swapfree"))
        self.gridLayout_2.addWidget(self.swapfree, 4, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_2.addWidget(self.label_22, 5, 0, 1, 1)
        self.swapused = QtGui.QLabel(self.gridLayoutWidget_2)
        self.swapused.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.swapused.setObjectName(_fromUtf8("swapused"))
        self.gridLayout_2.addWidget(self.swapused, 5, 1, 1, 1)
        self.tabbedPanel.addTab(self.memInfoTab, _fromUtf8(""))

        self.retranslateUi(Form)
        self.tabbedPanel.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "sysman", None))
        self.label_2.setText(_translate("Form", "CPU", None))
        self.label_3.setText(_translate("Form", "RAM", None))
        self.tabbedPanel.setTabText(self.tabbedPanel.indexOf(self.cpuLoadTab), _translate("Form", "CPU Aktywność", None))
        self.cpufreq.setText(_translate("Form", "cpu freq", None))
        self.label_4.setText(_translate("Form", "Częstotliwość", None))
        self.label.setText(_translate("Form", "Nazwa", None))
        self.cpucores.setText(_translate("Form", "cpu cores", None))
        self.cpumodel.setText(_translate("Form", "cpu model", None))
        self.flags.setText(_translate("Form", "flags", None))
        self.label_6.setText(_translate("Form", "Ilość rdzeni", None))
        self.label_8.setText(_translate("Form", "Instrukcje", None))
        self.label_10.setText(_translate("Form", "Rozmiar Cache", None))
        self.cpucache.setText(_translate("Form", "cpu cache", None))
        self.tabbedPanel.setTabText(self.tabbedPanel.indexOf(self.cpuInfoTab), _translate("Form", "CPU Info", None))
        self.memtotal.setText(_translate("Form", "memtotal", None))
        self.memfree.setText(_translate("Form", "memfree", None))
        self.label_14.setText(_translate("Form", "Dostępna pamięć", None))
        self.label_13.setText(_translate("Form", "Całkowita ilość pamięci", None))
        self.label_16.setText(_translate("Form", "Całkowita ilość pamięci SWAP", None))
        self.swaptotal.setText(_translate("Form", "swaptotal", None))
        self.label_18.setText(_translate("Form", "W użyciu RAM", None))
        self.memused.setText(_translate("Form", "memused", None))
        self.label_20.setText(_translate("Form", "Dostępna pamięć SWAP", None))
        self.swapfree.setText(_translate("Form", "swapfree", None))
        self.label_22.setText(_translate("Form", "W użyciu SWAP", None))
        self.swapused.setText(_translate("Form", "swapused", None))
        self.tabbedPanel.setTabText(self.tabbedPanel.indexOf(self.memInfoTab), _translate("Form", "RAM Info", None))

